{% set version = "1.3.2" %}

package:
  name: asyncio_extras
  version: {{ version }}

source:
  url: https://github.com/agronholm/asyncio_extras/archive/refs/tags/{{ version }}.tar.gz
  sha256: af41dbf28200d3a4e29ca3c2330d7d89ef08dd2554a4187ae92b3616f68d04a7

build:
  noarch: python
  number: 2
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  script_env: SETUPTOOLS_SCM_PRETEND_VERSION={{ version }}

requirements:
  host:
    - python
    - pip
  run:
    - python >=3.5
    - async_generator >=1.3

test:
  imports:
    - asyncio_extras

about:
  home: https://github.com/agronholm/asyncio_extras
  license: MIT
  license_file: LICENSE
  summary: Asynchronous generators, context managers and more for asyncio

extra:
  recipe-maintainers:
    - davidbrochart
