{% set version = "1.3.2" %}

package:
  name: asyncio_extras
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/a/asyncio_extras/asyncio_extras-{{ version }}.tar.gz
  sha256: 084b62bebc19c6ba106d438a274bbb5566941c469128cd4af1a85f00a2c81f8d

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - pip
  run:
    - python >=3.5
    - async_generator >=1.3

test:
  imports:
    - asyncio_extras

about:
  home: https://github.com/agronholm/asyncio_extras
  license: MIT
  license_file: LICENSE
  summary: Asynchronous generators, context managers and more for asyncio

extra:
  recipe-maintainers:
    - davidbrochart
